version: '2.4'

services:
  iris:
    image: store/intersystems/irishealth-community:2020.3.0.200.0
    init: true
    container_name: irishealth
    ports:
       - "52773:52773"
       - "1972:1972"
    environment:
      - ISC_DATA_DIRECTORY=/ISC/dur
      - TZ=JST-9
    volumes:
      - .:/ISC
  web:
    build: .
    init: true
    links:
      - iris
    ports:
      - 80:80
      - 443:443
    environment:
      SERVER_HOST: iris
      SERVER_PORT: 1972
